### PR TITLE
version bump to 0.4.9

### PR DESCRIPTION
**Pull request by ericmjl**

### CODE REVIEW

**Comment by ericmjl** [comment]
@conda-forge-admin, please rerender¶

**Comment by ericmjl** [comment]
@conda-forge-admin, please add noarch: python¶

**Comment by ericmjl** [comment]
@conda-forge-admin, please rerender

**Comment by ericmjl** [comment]
@conda-forge-admin, please add noarch: python

**Comment by ericmjl** [comment]
@proinsias I've made this a noarch Python package, re-rendered for conda-forge, and added myself as a recipe maintainer as well. All tests pass, please review when ready.

**Comment by ericmjl** [comment]
cc: @jakirkham @ocefpaf

**Comment by ocefpaf** [comment]
Thanks @ericmjl!

**Pull request merged**
